version: '3'
services:
  ubuntu:
    build: .
    volumes:
      - .:/code
    tty: true
    networks:
      - internal-network
      - external-network

networks:
  internal-network:
    internal: true
  external-network:
