all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      anisble_connection: local
      anisble_user: root
      ansible_sudo: yes
      ansible_python_interpreter: "{{ansible_playbook_python}}"
    containers:
      ansible_connection: docker
      ansible_host: anisble_playground_ubuntu_1
