all: # main group of hosts also can be used as `hosts` in playbook
  hosts:
    localhost: # name that will be used in playbooks as `hosts`
      # variables of that host
      ansible_host: 127.0.0.1
      anisble_connection: local # to not use ssh
      anisble_user: root
      ansible_sudo: yes
    ansible_playground_ubuntu_1: # name of host
      # variables of that host
      ansible_connection: docker # connect through docker not ssh
  children: #define that `all` group have children groups
    containers: # name of child group also can be used as `hosts` in playbook
      hosts:
        ansible_container: # name of host can be alias and  actual host can be define in variable: ansible_host
          # variables of that host
          ansible_connection: docker # connect through docker not ssh
          ansible_host: ansible_playground_ubuntu_1 # name of docker container or ip
